"""add google_id and password_reset_tokens

Revision ID: 504b18383ce1
Revises: 8293d4c5e989
Create Date: 2026-05-29 21:16:42.712783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504b18383ce1'
down_revision: Union[str, None] = '8293d4c5e989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Create password_reset_tokens only if it doesn't already exist
    if 'password_reset_tokens' not in inspector.get_table_names():
        op.create_table('password_reset_tokens',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('token', sa.String(length=128), nullable=False),
            sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('used', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    # Add google_id column and unique constraint only if column doesn't exist
    if 'users' in inspector.get_table_names():
        user_cols = [c['name'] for c in inspector.get_columns('users')]
        if 'google_id' not in user_cols:
            with op.batch_alter_table('users', schema=None) as batch_op:
                batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
                # Provide an explicit name for the unique constraint to avoid SQLite/Alembic errors
                batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Remove google_id if present
    if 'users' in inspector.get_table_names():
        user_cols = [c['name'] for c in inspector.get_columns('users')]
        if 'google_id' in user_cols:
            with op.batch_alter_table('users', schema=None) as batch_op:
                batch_op.drop_constraint('uq_users_google_id', type_='unique')
                batch_op.drop_column('google_id')

    # Drop password_reset_tokens and its indexes if present
    if 'password_reset_tokens' in inspector.get_table_names():
        with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
            batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

        op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
