"""add subscription_plan to users

Revision ID: 8293d4c5e989
Revises: 92058b966d3c
Create Date: 2026-05-21 20:31:20.595115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8293d4c5e989'
down_revision: Union[str, None] = '92058b966d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:batch_op.add_column(sa.Column('subscription_plan',sa.String(length=20),nullable=False,server_default='free',))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
